export const SAVE_BLOG_POSTS = "SAVE_BLOG_POSTS";
export const SAVE_BLOG_POST_DETAILS = "SAVE_BLOG_POST_DETAILS";
export const SAVE_BLOG_POST_COMMENTS = "SAVE_BLOG_POST_COMMENTS";
export const SAVE_TOTAL_BLOG_POSTS = "SAVE_TOTAL_BLOG_POSTS";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
